name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy theme to Shopify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Shopify CLI
        run: |
          curl -s https://shopify.dev/cli/install/linux | sh

      - name: Authenticate with Shopify
        env:
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_CLI_AUTH_TOKEN }}
        run: |
          shopify login --store ${{ secrets.SHOPIFY_STORE }}

      - name: Deploy theme
        run: |
          shopify theme push --path . --ignore ".gitignore"
                 - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Build assets
        run: npm run build
