name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Shopify CLI v3
        run: npm install -g @shopify/cli@3 @shopify/theme

      - name: Deploy to Shopify
        env:
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
          SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
        run: |
          shopify theme push --theme $SHOPIFY_THEME_ID --path . --store $SHOPIFY_STORE
