name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy theme
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Shopify CLI
        run: |
          curl -s https://shopify.dev/cli/install/linux | sh

      - name: Authenticate with Shopify
        env:
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_CLI_AUTH_TOKEN }}
        run: |
          shopify login --store ${{ secrets.SHOPIFY_STORE }}

      - name: Deploy to Shopify
        run: |
          shopify theme push --path . --ignore ".gitignore"
