name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Enable CLI token auth
        run: shopify config feature preview_shopify_cli_auth_token true

      - name: Deploy to Shopify
        run: |
          shopify theme push --path . \
            --store ${{ secrets.SHOPIFY_STORE_DOMAIN }} \
            --theme-id ${{ secrets.SHOPIFY_THEME_ID }} \
            --token ${{ secrets.SHOPIFY_ADMIN_API_TOKEN }}
