name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Validate theme
        env:
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHORTLY_PASSWORD }}
          NODE_OPTIONS: --max-old-space-size=4096
        run: shopify theme check

      - name: Deploy theme to Shopify
        env:
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHORTLY_PASSWORD }}
        run: |
          echo "🚀 Déploiement vers Shopify..."
          shopify theme push --path=. --store=thepetsociety.paris --allow-live --verbose
          echo "✅ Déploiement réussi!"

  notify_failure_if_any:
    needs: deploy
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Sentry of failure
        run: |
          EVENT_ID=$(uuidgen)
          PAYLOAD=$(cat <<EOF
          {
            "event_id": "$EVENT_ID",
            "timestamp": $(date +%s),
            "platform": "other",
            "message": "🚨 Échec du déploiement Shopify via GitHub Actions",
            "level": "error",
            "logger": "github-actions",
            "server_name": "github-actions",
            "release": "${{ github.sha }}",
            "tags": {
              "workflow": "${{ github.workflow }}",
              "repository": "${{ github.repository }}"
            },
            "extra": {
              "run_id": "${{ github.run_id }}",
              "run_number": "${{ github.run_number }}"
            }
          }
          EOF
          )
          curl -v -X POST "https://o4509330673303552.ingest.sentry.io/api/4509534073585744/envelope/" \
            -H "Content-Type: application/x-sentry-envelope" \
            -H "Authorization: DSN ${{ secrets.SHORTLY_STORE }}" \
            -d "$PAYLOAD"
