name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        working-directory: ./VORTEX-21JUIN2025

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Validate theme
        env:
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_CLI_AUTH_TOKEN }}
        run: shopify theme check
        working-directory: ./VORTEX-21JUIN2025

      - name: Deploy theme to Shopify
        env:
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_CLI_AUTH_TOKEN }}
        run: |
          echo "🚀 Déploiement vers Shopify..."
          echo "Boutique: thepetsociety.paris"
          echo "ID du thème: ${{ secrets.SHOPIFY_THEME_ID }}"
          shopify theme push --path=. --store=thepetsociety.paris --theme=${{ secrets.SHOPIFY_THEME_ID }} --allow-live --verbose
          echo "✅ Déploiement réussi!"
        working-directory: ./VORTEX-21JUIN2025

  notify_failure_if_any:
    needs: deploy
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Sentry of failure
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          echo "🚨 Envoi de la notification d'échec à Sentry"
          EVENT_ID=$(uuidgen)
          PAYLOAD=$(cat <<EOF
          {
            "event_id": "$EVENT_ID",
            "timestamp": $(date +%s),
            "platform": "other",
            "message": "Échec du déploiement Shopify via GitHub Actions",
            "level": "error",
            "logger": "github-actions",
            "server_name": "github-actions",
            "release": "${{ github.sha }}",
            "tags": {
              "workflow": "${{ github.workflow }}",
              "repository": "${{ github.repository }}"
            },
            "extra": {
              "run_id": "${{ github.run_id }}",
              "run_number": "${{ github.run_number }}"
            }
          }
          EOF
          )
          curl -v -X POST "https://o4509330673303552.ingest.sentry.io/api/4509534073585744/envelope/" \
            -H "Content-Type: application/x-sentry-envelope" \
            -H "Authorization: DSN ${{ secrets.SENTRY_DSN }}" \
            -d "$PAYLOAD"
          echo "📬 Notification envoyée à Sentry"
