name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload theme to Shopify
        uses: danielgroen/shopify-theme-upload-action@v1.0.3
        with:
          shopify_store: f6d72e-0f.myshopify.com
          theme_name: "VORTEX - 21JUIN2025"
          password: ${{ secrets.SHOPIFY_PASSWORD }}

      - name: Notify Sentry of deployment
        run: |
          curl https://sentry.io/api/0/organizations/falcon-trading/releases/ \
          -H "Authorization: Bearer ${{ secrets.SENTRY_AUTH_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "version": "vortex-${{ github.run_number }}",
            "projects": ["falcon-trading-sp"]
          }'
