name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload theme to Shopify
        uses: nueverest/shopify-upload-theme@v1.0.1
        with:
          store: ${{ secrets.SHOPIFY_STORE }}
          password: ${{ secrets.SHOPIFY_PASSWORD }}
          theme_id: ${{ secrets.SHOPIFY_THEME_ID }}
          directory: dist # ou ton dossier de thème

      - name: Notify Sentry of deployment
        run: |
          curl https://sentry.io/api/0/organizations/falcon-trading/releases/ \
          -H "Authorization: Bearer ${{ secrets.SENTRY_AUTH_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "version": "vortex-${{ github.run_number }}",
            "projects": ["falcon-trading-sp"]
          }'
