name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Deploy theme to Shopify
        env:
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_CLI_AUTH_TOKEN }}
          SHOPIFY_STORE: thepetsociety.paris
        run: |
          echo "🚀 Déploiement du thème vers Shopify..."
          shopify theme push --path=. --store=$SHOPIFY_STORE --allow-live
          echo "✅ Déploiement réussi !"

  notify_failure_if_any:
    needs: deploy
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Sentry of failure
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          EVENT_ID=$(uuidgen)
          TIMESTAMP=$(date +%s)
          echo "🚨 Échec du déploiement, notification à Sentry..."
          curl -X POST "https://sentry.io/api/0/organizations/falcon-trading/releases/" \
            -H "Authorization: Bearer $SENTRY_AUTH_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"version\": \"vortex-$GITHUB_RUN_NUMBER\",
              \"projects\": [\"falcon-trading-sp\"]
            }"
          echo "📬 Notification envoyée."
