name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Shopify theme
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Deploy theme to Shopify
        env:
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_CLI_AUTH_TOKEN }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
        run: |
          shopify theme push --path=. --store=thepetsociety.paris --allow-live

  notify_failure_if_any:
    name: Notify Sentry if deployment fails
    runs-on: ubuntu-latest
    needs: [deploy]
    if: failure()
    steps:
      - name: Notify Sentry of failure
        run: |
          curl -X POST https://o4509330673303552.ingest.de.sentry.io/api/4509534073585744/envelope/ \
          -H "Content-Type: application/json" \
          --data-raw "{
            \"dsn\": \"https://5d6ea3eb04284ce2f254e29083d3ddf7@o4509330673303552.ingest.de.sentry.io/4509534073585744\",
            \"event_id\": \"$(uuidgen)\",
            \"message\": \"🚨 Échec du déploiement Shopify via GitHub Actions\",
            \"level\": \"error\",
            \"platform\": \"other\",
            \"timestamp\": $(date +%s)
          }"
