name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy theme with Shopify CLI Docker
        run: |
          docker run --rm \
            -v "$PWD:/app" \
            -w /app \
            shopify/shopify-cli:latest \
            theme push \
            --store ${{ secrets.SHOPIFY_STORE }} \
            --password ${{ secrets.SHOPIFY_PASSWORD }} \
            --path . \
            --unpublished

      - name: Notify Sentry of deployment
        run: |
          curl https://sentry.io/api/0/organizations/falcon-trading/releases/ \
          -H "Authorization: Bearer ${{ secrets.SENTRY_AUTH_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "version": "vortex-${{ github.run_number }}",
            "projects": ["falcon-trading-sp"]
          }'
