name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@3 @shopify/theme

      - name: Deploy to Shopify
        env:
          SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}           # ex: thepetsociety-paris.myshopify.com
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}     # ID du thème à déployer
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}     # Mot de passe API (si utilisé)
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_CLI_AUTH_TOKEN }}  # Jeton d'authentification admin API
        run: |
          shopify theme push --store $SHOPIFY_STORE --theme $SHOPIFY_THEME_ID --path .
