name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Shopify
        uses: Shopify/shopify-cli-action@v1
        with:
          version: latest
        env:
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE }}
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_PASSWORD }}

      - name: Notify Sentry of deployment
        run: |
          curl https://sentry.io/api/0/organizations/falcon-trading/releases/ \
          -H "Authorization: Bearer ${{ secrets.SENTRY_AUTH_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "version": "vortex-${{ github.run_number }}",
            "projects": ["falcon-trading-sp"]
          }'
