name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'false'

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli

      - name: Validate theme
        env:
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_CLI_AUTH_TOKEN }}
          SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
        run: shopify theme check --store=$SHOPIFY_STORE --theme=$SHOPIFY_THEME_ID

      - name: Deploy theme to Shopify
        env:
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_CLI_AUTH_TOKEN }}
          SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
        run: |
          shopify theme push \
            --path=. \
            --store=$SHOPIFY_STORE \
            --theme=$SHOPIFY_THEME_ID \
            --allow-live

  notify_failure_if_any:
    needs: deploy
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Sentry of failure
        run: |
          curl -X POST https://o4509330673303552.ingest.sentry.io/api/4509534073585744/store/ \
            -H "Authorization: Bearer ${{ secrets.SENTRY_AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "message": "Déploiement Shopify échoué",
              "level": "error",
              "platform": "github-actions",
              "extra": {
                "run_id": "${{ github.run_id }}",
                "run_number": "${{ github.run_number }}"
              }
            }'
